### ISSUE TITLE
Deploying to Heroku app - looking for cmake in non-existent directory

### ISSUE THREAD

**Issue by stuartedward** [justadudewhohacks/face-recognition.js#120]
Building on a Mac. On attempting to deploy the project repo to Heroku, I see an error message relating to cmake not being found. 

```
 > dlib-build@0.1.1 install /tmp/build_21cacb0094414c1c66f553e59100ce04/node_modules/dlib-build
remote:        > node ./install.js
remote:
remote:        executing: git --version
remote:        executing: cmake --version
remote:        { Error: Command failed: cmake --version
remote:        /bin/sh: 1: cmake: not found
remote:
remote:        at ChildProcess.exithandler (child_process.js:273:12)
remote:        at ChildProcess.emit (events.js:127:13)
remote:        at maybeClose (internal/child_process.js:936:16)
remote:        at Socket.stream.socket.on (internal/child_process.js:353:11)
remote:        at Socket.emit (events.js:127:13)
remote:        at Pipe._handle.close [as _onclose] (net.js:558:12) killed: false, code: 127, signal: null, cmd: 'cmake --version' }
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! dlib-build@0.1.1 install: `node ./install.js`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the dlib-build@0.1.1 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.FXLK3/_logs/2018-08-23T09_42_37_427Z-debug.log
remote:
remote: -----> Build failed
```
I installed cmake with Homebrew but it did not save to usr/bin/sh. Is there a way to point the package to a different file path to retrieve the cmake build?

**Comment by stuartedward** [comment]
cmake build info

```
cmake: stable 3.12.1 (bottled), HEAD
Cross-platform make
https://www.cmake.org/
/usr/local/Cellar/cmake/3.12.1 (2,417 files, 33.6MB) *
  Poured from bottle on 2018-08-20 at 10:30:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cmake.rb
==> Dependencies
Build: sphinx-doc ✘
==> Options
--with-completion
        Install Bash completion (Has potential problems with system bash)
--without-docs
        Don't build man pages
--HEAD
        Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
```

**Comment by justadudewhohacks** [comment]
No there isnt, the cmake command has to be recognized by your system. I am pretty sure there is a way to link cmake runtime properly.
