### ISSUE TITLE
Error in FaceRecognizer -  Error: expected argument 0 to be of type ImageRGB

### ISSUE THREAD

**Issue by tanmaypatil** [justadudewhohacks/face-recognition.js#13]
Hi Vincent ,

I am trying to run sample code for face recognition in the page ( https://github.com/justadudewhohacks/face-recognition.js) .
I have done small changes as per local images i have . I have downloaded images from internet . 

My code : 
```
const fr = require('face-recognition');

const detector = fr.FaceDetector();

console.log("Loading  viraat images ");
const img1 = fr.loadImage('./viraatkohli.png');
const img2 = fr.loadImage('./viraatkohli2.png');

const vimg1  = detector.detectFaces(img1);
const vimg2  = detector.detectFaces(img2);

let  viraat_faces = [ ] ;
viraat_faces.push(vimg1);
viraat_faces.push(vimg2);

console.log("Loading  smith images ");
const smimg1 = fr.loadImage('./smith.png');
const smimg2 = fr.loadImage('./stevesmith2.png');

const vimg3  = detector.detectFaces(smimg1);
const vimg4  = detector.detectFaces(smimg2);

//const smith_faces = [ vimg3, vimg4] ;
let smith_faces = [];
smith_faces.push(vimg3);
smith_faces.push(vimg4);

console.log("Loading msd images ");
const msimg1 = fr.loadImage('./msdhoni.png');
const msimg2 = fr.loadImage('./msdhoni2.png');

const vimg5  = detector.detectFaces(msimg1);
const vimg6  = detector.detectFaces(msimg2);
let dhoni_faces = [];
dhoni_faces.push(vimg5);
dhoni_faces.push(vimg6);

const recognizer = fr.FaceRecognizer();

const numJitters = 15
recognizer.addFaces(smith_faces, 'smith',numJitters);
recognizer.addFaces(viraat_faces, 'viraat',numJitters);
recognizer.addFaces(dhoni_faces, 'msd',numJitters); 


console.log("running prediction");
const msimg3 = fr.loadImage('./msdhoni3.jpg');

const faceImage = detector.detectFaces(msimg3);
const predictions = recognizer.predictBest(faceImage);
console.log(predictions);


```

I get following stack trace . 
```
 node starter3.js
Loading  viraat images
Loading  smith images
Loading msd images
D:\face_recognition_node\node_modules\face-recognition\lib\src\FaceRecognizer.js:59
      return [face].concat(!numJitters ? [] : fr.jitterImage(face, numJitters))
                                                 ^

Error: JitterImage - Error: expected argument 0 to be of type ImageRGB
    at getJitteredFaces (D:\face_recognition_node\node_modules\face-recognition\lib\src\FaceRecognizer.js:59:50)
    at faces.map.f (D:\face_recognition_node\node_modules\face-recognition\lib\src\FaceRecognizer.js:81:24)
    at Array.map (<anonymous>)
    at Object.addFaces (D:\face_recognition_node\node_modules\face-recognition\lib\src\FaceRecognizer.js:81:15)
    at Object.<anonymous> (D:\face_recognition_node\starter3.js:43:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
 node starter3.js
Loading  viraat images
Loading  smith images
Loading msd images
D:\face_recognition_node\node_modules\face-recognition\lib\src\FaceRecognizer.js:59
      return [face].concat(!numJitters ? [] : fr.jitterImage(face, numJitters))
                                                 ^
```

Do i need some kind of image processing to convert images into RGB format ? 

Regards
Tanmay

**Comment by justadudewhohacks** [comment]
Hey,

`const vimg1  = detector.detectFaces(img1);` vimg1  will be an array with all face images, e.g an array of `ImageRGB`. Now if you are pushing them into `viraat_faces `, you will end up with an array of arrays of `ImageRGB`, which is why the API complains.

Instead do something like this: `let  viraat_faces = vimg1.concat(vimg2);`

**Comment by tanmaypatil** [comment]
Yes Thanks working fine now .

Code : post change 
```
const fr = require('face-recognition');

const detector = fr.FaceDetector();

console.log("Loading  viraat images ");
const img1 = fr.loadImage('./viraatkohli.jpg');
const img2 = fr.loadImage('./viraatkohli2.jpg');

const vimg1  = detector.detectFaces(img1);
const vimg2  = detector.detectFaces(img2);

let  viraat_faces = [] ;
viraat_faces = vimg1.concat(vimg2);

console.log("Loading  smith images ");
const smimg1 = fr.loadImage('./stevesmith3.jpg');
const smimg2 = fr.loadImage('./stevesmith2.jpg');

const vimg3  = detector.detectFaces(smimg1);
const vimg4  = detector.detectFaces(smimg2);

//const smith_faces = [ vimg3, vimg4] ;
let smith_faces = [];
smith_faces = vimg3.concat(vimg4);
console.log("post smith");

console.log("Loading msd images ");
const msimg1 = fr.loadImage('./msdhoni.png');
const msimg2 = fr.loadImage('./msdhoni2.png');

const vimg5  = detector.detectFaces(msimg1);
const vimg6  = detector.detectFaces(msimg2);
let dhoni_faces = [] ;
dhoni_faces = vimg5.concat(vimg6);

console.log(" Post dhoni faces");
const recognizer = fr.FaceRecognizer();

const numJitters = 15
recognizer.addFaces(smith_faces, 'smith',numJitters);
recognizer.addFaces(viraat_faces, 'viraat',numJitters);
recognizer.addFaces(dhoni_faces, 'msd',numJitters); 


console.log("running prediction");
const msimg3 = fr.loadImage('./msdhoni3.jpg');

const faceImage = detector.detectFaces(msimg3);
if ( Array.isArray(faceImage)) {
    console.log("is array");
}
else {
    console.log("not a array");
}

const predictionsAll = recognizer.predict(faceImage[0]);
console.log(predictionsAll);
const predictions = recognizer.predictBest(faceImage[0]);
console.log(predictions);



```
