### ISSUE TITLE
Unable to install, Command fail

### ISSUE THREAD

**Issue by Omega7569** [justadudewhohacks/face-recognition.js#131]
Hello,

every time I'm trying to install this package I'm getting the following error :

` face-recognition@0.9.3 install E:\Development\Web\Security\node_modules\face-recognition
> node-gyp rebuild

E:\Development\Web\Security\node_modules\face-recognition>if not defined npm_config_node_gyp (node "E:\Software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "E:\Software\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: E:\Software\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "E:\\Software\\nodejs\\node.exe" "E:\\Software\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Development\Web\Security\node_modules\face-recognition
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN security@1.0.0 No description
npm WARN security@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the face-recognition@0.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\louis\AppData\Roaming\npm-cache\_logs\2018-10-19T23_58_53_157Z-debug.log`

I have reinstalled python, node-gyp, dlib-build but it's still not working

**Comment by Chuiantw1212** [comment]
I got this one also. It also happens to you with python3.7+windows I bet. Try downgrade the Python version.
