### ISSUE TITLE
Can`t install face-recognition with npm !!!

### ISSUE THREAD

**Issue by brunoals** [justadudewhohacks/face-recognition.js#136]
Please HELP!!

When I execute the sudo npm install face-recognition the following error appears:
executing: git --version
executing: cmake --version
executing: mkdir -p dlib
{ Error: Command failed: mkdir -p dlib
mkdir: dlib: Permission denied

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12) killed: false, code: 1, signal: null, cmd: 'mkdir -p dlib' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlib-build@0.1.1 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dlib-build@0.1.1 install script.
------------------------------
The log file:
 verbose stack Error: dlib-build@0.1.1 install: `node ./install.js`
97 verbose stack Exit status 1
97 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
97 verbose stack     at EventEmitter.emit (events.js:182:13)
97 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
97 verbose stack     at ChildProcess.emit (events.js:182:13)
97 verbose stack     at maybeClose (internal/child_process.js:962:16)
97 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
98 verbose pkgid dlib-build@0.1.1
99 verbose cwd /Users/xuser/Project/FACE-RECOGNITION/SYSTEM/facerecog
100 verbose Darwin 17.2.0
101 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "dlib-build"
102 verbose node v11.0.0
103 verbose npm  v6.4.1
104 error code ELIFECYCLE
105 error errno 1
106 error dlib-build@0.1.1 install: `node ./install.js`
106 error Exit status 1
107 error Failed at the dlib-build@0.1.1 install script.
107 error This is probably not a problem with npm. There is likely additional logging output above.
108 verbose exit [ 1, true ]

**Comment by justadudewhohacks** [comment]
Try npm install without sudo.
