### ISSUE TITLE
npm install does not work

### ISSUE THREAD

**Issue by davejack1** [justadudewhohacks/face-recognition.js#149]
Simply tried `npm install face-recognition --save` and `npm install face-recognition`. Also tried with `sudo`. I only get the following error;

```
executing: git --version
executing: cmake --version
{ Error: Command failed: cmake --version
/bin/sh: cmake: command not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) killed: false, code: 127, signal: null, cmd: 'cmake --version' }
npm WARN lock@1.0.0 No description
npm WARN lock@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlib-build@0.1.1 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dlib-build@0.1.1 install script.
```

Any ideas @justadudewhohacks ?

**Comment by MohannadBakkar** [comment]
Hi @davejack1, I think you need to install **cmake**, I hope this [link](https://cmake.org/install/) helpful for you.

**Comment by qiyaozu** [comment]
@MohannadBakkar i have install the cmake and link that,the same not to install
