### ISSUE TITLE
"unresolved external symbol" on Manual build

### ISSUE THREAD

**Issue by giangvincent** [justadudewhohacks/face-recognition.js#152]
$ npm install face-recognition --save

> dlib-build@0.1.1 install E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\dlib-build
> node ./install.js

found dlib
DLIB_INCLUDE_DIR: E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\dlib-master
DLIB_LIB_DIR: E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\dlib-master\build\temp.win-amd64-2.7\Release\Release

> face-recognition@0.9.4 install E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition
> node-gyp rebuild

E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
cl : Command line warning D9025: overriding '/MT' with '/MD' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/MT' with '/MD' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/MT' with '/MD' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
  index.cc
cl : Command line warning D9025: overriding '/MT' with '/MD' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
  ImageRGB.cc
cl : Command line warning D9025: overriding '/MT' with '/MD' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
  ImageGray.cc
  CvImage.cc
  Rect.cc
  MmodRect.cc
  FullObjectDetection.cc
  Point.cc
  Array.cc
  ChipDetails.cc
  utils.cc
  ImageWindow.cc
  ShapePredictor.cc
  FrontalFaceDetector.cc
  FaceDetectorNet.cc
  FaceRecognizerNet.cc
     Creating library E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\Release\facerec.lib and object E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\Release\facerec.exp
index.obj : error LNK2001: unresolved external symbol USER_ERROR__inconsistent_build_configuration__see_dlib_faq_1_ [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
index.obj : error LNK2001: unresolved external symbol USER_ERROR__inconsistent_build_configuration__see_dlib_faq_2 [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::save_jpeg(class dlib::array2d<struct dlib::rgb_pixel,class dlib::memory_manager_stateless_kernel_1<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?save_jpeg@dlib@@YAXAEBV?$array2d@Urgb_pixel@dlib@@V?$memory_manager_stateless_kernel_1@D@2@@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::save_jpeg(class dlib::array2d<unsigned char,class dlib::memory_manager_stateless_kernel_1<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?save_jpeg@dlib@@YAXAEBV?$array2d@EV?$memory_manager_stateless_kernel_1@D@dlib@@@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "private: unsigned char const * __cdecl dlib::png_loader::get_row(unsigned int)const " (?get_row@png_loader@dlib@@AEBAPEBEI@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: bool __cdecl dlib::png_loader::is_rgba(void)const " (?is_rgba@png_loader@dlib@@QEBA_NXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: bool __cdecl dlib::png_loader::is_rgb(void)const " (?is_rgb@png_loader@dlib@@QEBA_NXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: bool __cdecl dlib::png_loader::is_graya(void)const " (?is_graya@png_loader@dlib@@QEBA_NXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: bool __cdecl dlib::png_loader::is_gray(void)const " (?is_gray@png_loader@dlib@@QEBA_NXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::png_loader::~png_loader(void)" (??1png_loader@dlib@@QEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::png_loader::png_loader(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0png_loader@dlib@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: unsigned int __cdecl dlib::entropy_decoder_kernel_2::get_target(unsigned int)" (?get_target@entropy_decoder_kernel_2@dlib@@QEAAII@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::entropy_decoder_kernel_2::decode(unsigned int,unsigned int)" (?decode@entropy_decoder_kernel_2@dlib@@QEAAXII@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::entropy_decoder_kernel_2::set_stream(class std::basic_istream<char,struct std::char_traits<char> > &)" (?set_stream@entropy_decoder_kernel_2@dlib@@QEAAXAEAV?$basic_istream@DU?$char_traits@D@std@@@std@@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl dlib::entropy_decoder_kernel_2::~entropy_decoder_kernel_2(void)" (??1entropy_decoder_kernel_2@dlib@@UEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::entropy_decoder_kernel_2::entropy_decoder_kernel_2(void)" (??0entropy_decoder_kernel_2@dlib@@QEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::impl::impl_save_png(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<unsigned char *,class std::allocator<unsigned char *> > &,long,enum dlib::impl::png_type,int)" (?impl_save_png@impl@dlib@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@PEAEV?$allocator@PEAE@std@@@4@JW4png_type@12@H@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: bool __cdecl dlib::jpeg_loader::is_rgba(void)const " (?is_rgba@jpeg_loader@dlib@@QEBA_NXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: bool __cdecl dlib::jpeg_loader::is_gray(void)const " (?is_gray@jpeg_loader@dlib@@QEBA_NXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
utils.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::jpeg_loader::jpeg_loader(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0jpeg_loader@dlib@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::image_window::clear_overlay(void)" (?clear_overlay@image_window@dlib@@QEAAXXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::image_window::add_overlay(struct dlib::image_display::overlay_rect const &)" (?add_overlay@image_window@dlib@@QEAAXAEBUoverlay_rect@image_display@2@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::image_window::add_overlay(class std::vector<struct dlib::image_display::overlay_line,class std::allocator<struct dlib::image_display::overlay_line> > const &)" (?add_overlay@image_window@dlib@@QEAAXAEBV?$vector@Uoverlay_line@image_display@dlib@@V?$allocator@Uoverlay_line@image_display@dlib@@@std@@@std@@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl dlib::image_window::~image_window(void)" (??1image_window@dlib@@UEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::image_window::image_window(void)" (??0image_window@dlib@@QEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: class dlib::rectangle __cdecl dlib::image_display::get_image_display_rect(void)const " (?get_image_display_rect@image_display@dlib@@QEBA?AVrectangle@2@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::draw_sunken_rectangle(class dlib::canvas const &,class dlib::rectangle const &,unsigned char)" (?draw_sunken_rectangle@dlib@@YAXAEBVcanvas@1@AEBVrectangle@1@E@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "protected: void __cdecl dlib::scrollable_region::set_total_rect_size(unsigned long,unsigned long)" (?set_total_rect_size@scrollable_region@dlib@@IEAAXKK@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::base_window::invalidate_rectangle(class dlib::rectangle const &)" (?invalidate_rectangle@base_window@dlib@@QEAAXAEBVrectangle@2@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::base_window::set_size(int,int)" (?set_size@base_window@dlib@@QEAAXHH@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
ImageWindow.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::base_window::close_window(void)" (?close_window@base_window@dlib@@QEAAXXZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FrontalFaceDetector.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::base64::decode(class std::basic_istream<char,struct std::char_traits<char> > &,class std::basic_ostream<char,struct std::char_traits<char> > &)const " (?decode@base64@dlib@@QEBAXAEAV?$basic_istream@DU?$char_traits@D@std@@@std@@AEAV?$basic_ostream@DU?$char_traits@D@std@@@4@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FrontalFaceDetector.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl dlib::base64::~base64(void)" (??1base64@dlib@@UEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FrontalFaceDetector.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::base64::base64(void)" (??0base64@dlib@@QEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceDetectorNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::relu(class dlib::tensor &,class dlib::tensor const &)" (?relu@tt@dlib@@YAXAEAVtensor@2@AEBV32@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceDetectorNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::affine_transform_conv(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor const &)" (?affine_transform_conv@tt@dlib@@YAXAEAVtensor@2@AEBV32@11@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceDetectorNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::resize_bilinear(class dlib::tensor &,long,long,class dlib::tensor const &,long,long)" (?resize_bilinear@tt@dlib@@YAXAEAVtensor@2@JJAEBV32@JJ@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceDetectorNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::add(float,class dlib::tensor &,float,class dlib::tensor const &)" (?add@tt@dlib@@YAXMAEAVtensor@2@MAEBV32@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceDetectorNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::affine_transform(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor const &)" (?affine_transform@tt@dlib@@YAXAEAVtensor@2@AEBV32@11@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceDetectorNet.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::cpu::tensor_conv::operator()(bool,class dlib::resizable_tensor &,class dlib::tensor const &,class dlib::tensor const &)" (??Rtensor_conv@cpu@dlib@@QEAAX_NAEAVresizable_tensor@2@AEBVtensor@2@2@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceRecognizerNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::gemm(float,class dlib::tensor &,float,class dlib::tensor const &,bool,class dlib::tensor const &,bool)" (?gemm@tt@dlib@@YAXMAEAVtensor@2@MAEBV32@_N12@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceRecognizerNet.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::tt::add(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &)" (?add@tt@dlib@@YAXAEAVtensor@2@AEBV32@1@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceRecognizerNet.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::cpu::pooling::operator()(class dlib::resizable_tensor &,class dlib::tensor const &)" (??Rpooling@cpu@dlib@@QEAAXAEAVresizable_tensor@2@AEBVtensor@2@@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceRecognizerNet.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::cpu::pooling::setup_avg_pooling(int,int,int,int,int,int)" (?setup_avg_pooling@pooling@cpu@dlib@@QEAAXHHHHHH@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceRecognizerNet.obj : error LNK2001: unresolved external symbol "public: void __cdecl dlib::cpu::pooling::setup_max_pooling(int,int,int,int,int,int)" (?setup_max_pooling@pooling@cpu@dlib@@QEAAXHHHHHH@Z) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
FaceRecognizerNet.obj : error LNK2001: unresolved external symbol "public: __cdecl dlib::cpu::pooling::pooling(void)" (??0pooling@cpu@dlib@@QEAA@XZ) [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\Release\facerec.node : fatal error LNK1120: 46 unresolved externals [E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition\build\facerec.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\xampp\htdocs\projects\google_app\render\facedetect_allquiz_net_2\node_modules\face-recognition
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN counter_allquiz_api@1.0.0 No description
npm WARN counter_allquiz_api@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the face-recognition@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by usavdev** [comment]
How solve this problem?
