### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by qiyaozu** [justadudewhohacks/face-recognition.js#155]
i have brew unlink tesseract and rm node_modules,the same issues

18 warnings and 18 errors generated.
make: *** [Release/obj.target/facerec/cc/index.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/qiyaozu/node_test/face-recognition.js
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the face-recognition@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qiyaozu/.npm/_logs/2019-07-11T04_09_33_198Z-debug.log

**Comment by MukeshKalaga** [comment]
Did it solve?
or
What alternative did u use?

**Comment by uwe72** [comment]
Is there a solution? i have the same error:
npm ERR! face-recognition@0.9.4 install: `node-gyp rebuild`

**Comment by DavideVito** [comment]
I have the same problem, I'm on macOS
