### ISSUE TITLE
face-recognition.js installation error

### ISSUE THREAD

**Issue by iamsome1** [justadudewhohacks/face-recognition.js#39]
I am getting below error when I try to install using npm install face-recognition command windows 10.
```
const { dlibLocalLib } = require('./constants')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
 npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "face-recognition"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! dlib-build@0.0.6 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dlib-build@0.0.6 install script 'node ./install.js'.
npm ERR! This is most likely a problem with the dlib-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dlib-build
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls dlib-build
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\New folder\faceDetect\npm-debug.log
```

**Comment by justadudewhohacks** [comment]
Hi,

node v4.4.7 does not support destructuring syntax, that's why you are receiving this error. Try any node version above v6.
