### ISSUE TITLE
Install issue on Windows 7

### ISSUE THREAD

**Issue by pratikgchaudhari** [justadudewhohacks/face-recognition.js#4]
Hi,
I am using my own build of [**dlib**.](https://github.com/davisking/dlib) 
I have set the **DLIB_INCLUDE_DIR** & **DLIB_LIB_DIR** in windows PATH variable as specified in the README.
But I am getting following error on running `npm i face-recognition`:

F:\Projects\face-recognition-demo\node_modules\face-recognition\lib\includes.js:4
  ? resolvePath(DLIB_INCLUDE_DIR)
                ^
ReferenceError: DLIB_INCLUDE_DIR is not defined
    at Object.<anonymous> (F:\Projects\face-recognition-demo\node_modules\face-recognition\lib\includes.js:4:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

OS: Windows 7, 64-bit
Node: 8.6.0
npm: 5.3.0

**Comment by justadudewhohacks** [comment]
Yea it has to be process.env.DLIB_INCLUDE_DIR of course.

**Comment by justadudewhohacks** [comment]
@iamblue  kindly fixed this with #5, so in case you need this urgently, you can clone the repo instead of installing by npm. Otherwise I will publish a new release as soon as I have access to npm.

**Comment by justadudewhohacks** [comment]
Published.

**Comment by pratikgchaudhari** [comment]
Just installed the latest version. It's working fine now.
Thanks again!
