### ISSUE TITLE
Problems with npm install and windows

### ISSUE THREAD

**Issue by AlbuquerqueRafael** [justadudewhohacks/face-recognition.js#46]
Node: 8.9.1
OS: Windows 10, 64bit, v1709
Microsoft Build Engine version: 14.0.24720.0
CMAKE: 3.11.0-rc1

I just tried to install face-recognition and I receive this error: 

`> 
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rafael Albuquerque\Documents\workspace\visao\node_modules\face-recognition
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN visao@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the face-recognition@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

I have both node-gyp and rebuild installed globally.
Also, during the install, I receive a lot of warnings.
Ex:
`c:\users\rafael albuquerque\documents\workspace\visao\node_modules\face-recognition\cc\FaceRecognizerNet.h(2): fatal error C1083: Not possible open the file include::
 'dlib/dnn.h': No such file or directory (compilando arquivo de origem ..\cc\FaceRecognizerNet.cc) [C:\Users\Rafael Albuquerque\Documents\workspace\visao\node_modules\
face-recognition\build\facerec.vcxproj]`

**Comment by justadudewhohacks** [comment]
Did the auto build of dlib complete without any errors?

**Comment by AlbuquerqueRafael** [comment]
Yep. No errors and no warnings. I already tried to change SDK, change vs version(2017 -> 2015) and nothing seems to work.

**Comment by justadudewhohacks** [comment]
Odd, so if the auto build really finished successfully then you should have a clone of the dlib repo in `node_modules/dlib_build/dlib` and a `dlib.lib` file should exist in `node_modules/dlib_build/build/dlib/Release/lib`.

If you do not have these, then I need the full npm log and you could try to `npm install dlib-build` again. If you do, then there is either something wrong with the dlib include path on your system or you have set a DLIB_INCLUDE_DIR env variable, which is pointing to a wrong location.

By the way vs2015 won't work, stick with vs2017.

**Comment by AlbuquerqueRafael** [comment]
Yep, like I say, no errors and no warnings. 

![image](https://user-images.githubusercontent.com/13631723/36625614-ca7bb906-1901-11e8-84f9-9de301430834.png)

Do you want dlib logs or face-recognition  logs?

**Comment by AlbuquerqueRafael** [comment]
Nops. I tried a lot of things and in the end, I just gave up.  I decided to use another solution to resolve my problem with face recognition.

**Comment by blazerfanbc** [comment]
+1 same exact problem.

**Comment by justadudewhohacks** [comment]
Not sure if thats the issue, but whenever people report that issue, they have a whitespace in their path.

**Comment by blazerfanbc** [comment]
You were 100% correct. I had my project in a folder called "Visual Studio". That space is what did it. It's working now, thanks for the suggestion!

**Comment by DeonNel1** [comment]
@justadudewhohacks i'm stuck with the same error.  Which path should I check for spaces?  I've tried everything from removing/reinstalling node node-gyp changing windows 10 sdk version etc...  Any idea what else I can check?

**Comment by justadudewhohacks** [comment]
Actually I am talking about the path, where you execute node/npm, your current working directory. Apparently `fs.exists` doesn't like paths with whitespaces in it. So, you are also confronted with `fatal error C1083: Not possible open the file include:: 'dlib/dnn.h': No such file or directory`?

**Comment by DeonNel1** [comment]
@justadudewhohacks it seemed to be the same error at first as it complained about gyp-rebuild but i'm not entirely sure.  I've attached my output log.  This seems to be a real pain to build in windows, it took me a day to try compile openBlas and I eventually found a pre-compiled (older version) but not sure at 
[node-face-recognition-errorLog.txt](https://github.com/justadudewhohacks/face-recognition.js/files/2209659/node-face-recognition-errorLog.txt)
all how to proceed from here with this node-gyp error...

**Comment by DeonNel1** [comment]
i'm using the auto build dlib package.  Should I try build it myself?

**Comment by justadudewhohacks** [comment]
That's odd, usually with the default cmake configuration dlib should automatically configure this for you. Maybe this [issue ](https://stackoverflow.com/questions/38115070/libpng-function-calls-are-all-unresolved-external-symbols) helps you. If you need to set cmake specific flags I would suggest you to build dlib on your own.

**Comment by DeonNel1** [comment]
i've never used libpng, what I took from that was that I should make sure I build for 32/64bit?  Doesn't node handle the dlib build during auto build?  If so how can I see which architecture it's trying to build for?

**Comment by justadudewhohacks** [comment]
What I wanted to say is, that it seems like on your machine dlib is linked against a custom libpng instance. I think by default dlib should just build libpng from it's externals folder, but it looks like it does not build or link it properly in your case.

I would try to build dlib on your own first, or watch the cmake output of the auto build for some libpng specific output.
