### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by PawanWagh** [justadudewhohacks/face-recognition.js#56]
This is where the error occurs - 
```
XX(target) Release/obj.target/facerec/cc/index.o
In file included from ../cc/index.cc:1:
In file included from ../../nan/nan.h:51:
In file included from /Users/shashikantsharma/.node-gyp/6.9.2/include/node/node.h:42:
In file included from /Users/shashikantsharma/.node-gyp/6.9.2/include/node/v8.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:157:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:16:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:309:44: fatal error: 
      recursive template instantiation exceeded maximum depth of 256
{typedef typename remove_volatile<typename remove_const<_Tp>::type>::type type;};
```

1 error generated.
make: *** [Release/obj.target/facerec/cc/index.o] Error 1
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/shashikantsharma/Sites/faceRecognition/node_modules/face-recognition
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN faceRecognition@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "face-recognition"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! face-recognition@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the face-recognition@0.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the face-recognition package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs face-recognition
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls face-recognition
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shashikantsharma/Sites/faceRecognition/npm-debug.log
```

**Comment by justadudewhohacks** [comment]
What's you c++ version. This package needs atleast c++ 11 to compile.

**Comment by PawanWagh** [comment]
I have c++ 11, see this
`
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Configuring done
-- Generating done
```
Then also I have updated to c++ 11 and now build fails with error ```c++: error: unrecognized command line option '-stdlib=libc++'```.

**Comment by justadudewhohacks** [comment]
Hm I am not sure how to set up a working c++ environment with stdlib on mac, but on travis it worked right out of the box with xcode version 8.3 I think.

Otherwise googling the issue should give you quite some hints about how to fix this.

**Comment by PawanWagh** [comment]
Ok, thanks.

**Comment by asilvas** [comment]
@PawanWagh did you ever find a resolution to the original issue? All my deps are up to date, and I've never had this issue with other compiled packages.
