### ISSUE TITLE
sudo npm install -g face-recognition fails

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/face-recognition.js#91]
```
> dlib-build@0.1.1 install /usr/lib/node_modules/face-recognition/node_modules/dlib-build
> node ./install.js

executing: git --version
executing: cmake --version
executing: mkdir -p dlib
{ Error: Command failed: mkdir -p dlib
mkdir: cannot create directory ‘dlib’: Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12) killed: false, code: 1, signal: null, cmd: 'mkdir -p dlib' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlib-build@0.1.1 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dlib-build@0.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/komal/.npm/_logs/2018-05-21T09_57_57_634Z-debug.log

```

**Comment by justadudewhohacks** [comment]
The node process doesn't have permissions to create directories in your global node_modules folder, thus npm i -g won't work. Why do you want to install it globally?

**Comment by komalpharate** [comment]
Okay. Thank you.
I just tried so I wont have to install it again.

**Comment by justadudewhohacks** [comment]
Fair enough, you could simply install it to some folder and have your projects require it from there.
