### ISSUE TITLE
unable to run any program in examples folder

### ISSUE THREAD

**Issue by saiparvathi** [justadudewhohacks/face-recognition.js#97]
Hi,
I am new to nodejs even dont know how to run node js files 
I have runned an example program of facedetection.js and left with following error

on linx ubuntu
command ----- node faceDetection.js

err-------

module.js:457
    throw err;
    ^

Error: Cannot find module '../build/Release/facerec'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/paru/sdl/face_node/face-recognition.js/lib/fr.js:6:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

I am facing the same error for all the programs in example folder
node == v6.6.0
npm == 3.10.3

Can anyone help me out to solve this error or am I supposed to run differently???
Thank you.

**Comment by justadudewhohacks** [comment]
Hi, looks like you didnt run npm install in the root folder after cloning the repo, or the installation had errors
